# Generated by Django 4.2.1 on 2023-10-12 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sustainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=300, null=True)),
                ('joined', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, choices=[('GA', 'Georgia')], max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('linked_in', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
