# Generated by Django 4.2.1 on 2023-10-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainer',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sustainer',
            name='state',
            field=models.CharField(blank=True, choices=[('GA', 'Georgia')], max_length=25, null=True),
        ),
    ]
