# Generated by Django 4.2.6 on 2023-10-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sustainer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics/"
            ),
        ),
    ]
