# Generated by Django 4.2.1 on 2023-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sustainer_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainer',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='users.sustainer'),
        ),
    ]
