# Generated by Django 4.2.6 on 2023-10-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sustainer_following_alter_sustainer_state'),
        ('users', '0005_alter_sustainer_state'),
    ]

    operations = [
    ]
