# Generated by Django 4.2.1 on 2023-10-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_sustainer_city_alter_sustainer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('text', models.TextField(blank=True, max_length=100, null=True)),
                ('sustainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sustainer')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('sustainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sustainer')),
            ],
        ),
        migrations.CreateModel(
            name='Commment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('sustainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sustainer')),
            ],
        ),
    ]
