# Generated by Django 4.2.6 on 2023-10-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('completionStatus', models.BooleanField(blank=True, default=False, null=True)),
                ('sustainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sustainer')),
            ],
        ),
    ]
