# Generated by Django 4.2.6 on 2023-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
