# Generated by Django 4.2.1 on 2023-10-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='cause',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='completionStatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
